BUG: Fix failing to install optional dependencies during selective install
subprocess.CalledProcessError: Command '['C:/Users/butlej30383/AppData/Local/slicer.org/Slicer 5.6.2/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'black;extra', '==', 'dev']' returned non-zero exit status 2.

(cherry picked from commit 2d764fb116967fb6c42193fd1fe3c6b920a4379d)